#pragma once

#include <cstdint>
#include <string>

/*
 * LiveProgressReporter
 *
 * Sends authoritative progress generated by the native C++ operation
 * to the SecureWipe backend.
 *
 * Important:
 * - The native operation remains the source of truth.
 * - This class only reports progress.
 * - It does NOT calculate progress from GUI state.
 * - It does NOT run another sanitization/forensic operation.
 * - Network failure must never corrupt or stop the underlying native
 *   storage operation.
 */

class LiveProgressReporter
{
public:
    enum class OperationType
    {
        SANITIZATION,
        FORENSIC
    };

    struct Config
    {
        std::string baseUrl;
        std::string token;

        /*
         * Minimum interval between network updates.
         *
         * Native engines can generate many progress callbacks.
         * We do not want one HTTP request for every callback.
         */
        std::uint64_t minimumUpdateIntervalMs = 1000;

        /*
         * Always send when progress reaches 0 or 100.
         */
        bool alwaysSendBoundaryProgress = true;
    };

    LiveProgressReporter(
        OperationType operationType,
        const std::string& operationId,
        const Config& config);

    ~LiveProgressReporter();

    LiveProgressReporter(
        const LiveProgressReporter&) = delete;

    LiveProgressReporter& operator=(
        const LiveProgressReporter&) = delete;

    LiveProgressReporter(
        LiveProgressReporter&&) = delete;

    LiveProgressReporter& operator=(
        LiveProgressReporter&&) = delete;

    /*
     * Sanitization progress.
     */
    bool reportSanitizationProgress(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Forensic progress.
     *
     * Candidate/recovery counters are sent along with the byte progress
     * so the website can display the complete live forensic state.
     */
    bool reportForensicProgress(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Explicit final update.
     *
     * These bypass throttling so the backend always receives the
     * terminal state.
     */
    bool finishSanitization(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message = {});

    bool finishForensic(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Disable network reporting without affecting the native operation.
     */
    void disable();

    bool enabled() const;

private:
    OperationType operationType_;
    std::string operationId_;
    Config config_;

    bool enabled_ = false;

    std::uint64_t lastSentAtMs_ = 0;
    int lastPercentage_ = -1;

    bool shouldSend(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        bool force) const;

    bool sendSanitizationRequest(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message,
        bool force);

    bool sendForensicRequest(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message,
        bool force);

    static std::uint64_t nowMs();

    static int calculatePercentage(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes);

    static std::string escapeJson(
        const std::string& value);

    static std::string joinUrl(
        const std::string& baseUrl,
        const std::string& path);

    bool postJson(
        const std::string& url,
        const std::string& jsonBody);
};