#pragma once

#include <cstdint>
#include <string>

/*
 * LiveProgressReporter
 *
 * Reports progress generated by the actual native operation
 * to the SecureWipe backend.
 *
 * IMPORTANT:
 *
 * resourceId:
 *   - sanitization requestId
 *   - forensic caseId
 *
 * operationId:
 *   - unique identifier of the actual native execution
 *
 * The native operation remains the source of truth.
 *
 * This class:
 *   - does NOT perform sanitization
 *   - does NOT perform forensic scanning
 *   - does NOT calculate fake device progress
 *   - does NOT depend on Qt
 *   - does NOT stop the native operation when the backend
 *     is unavailable
 *
 * Network reporting is therefore auxiliary to the destructive
 * storage operation.
 */

class LiveProgressReporter
{
public:
    enum class OperationType
    {
        SANITIZATION,
        FORENSIC
    };

    struct Config
    {
        std::string baseUrl;
        std::string token;

        /*
         * Minimum time between normal progress requests.
         *
         * Native operations can generate many callbacks.
         * Reporting every callback would unnecessarily load
         * the backend.
         */
        std::uint64_t minimumUpdateIntervalMs = 1000;

        /*
         * Always send boundary states:
         *
         *   0%
         *   100%
         *
         * Boundary updates bypass throttling.
         */
        bool alwaysSendBoundaryProgress = true;
    };

    /*
     * resourceId:
     *
     * SANITIZATION -> requestId
     * FORENSIC     -> caseId
     *
     * operationId:
     *
     * unique identifier of the native execution.
     */
    LiveProgressReporter(
        OperationType operationType,
        const std::string& resourceId,
        const std::string& operationId,
        const Config& config);

    ~LiveProgressReporter();

    LiveProgressReporter(
        const LiveProgressReporter&) = delete;

    LiveProgressReporter& operator=(
        const LiveProgressReporter&) = delete;

    LiveProgressReporter(
        LiveProgressReporter&&) = delete;

    LiveProgressReporter& operator=(
        LiveProgressReporter&&) = delete;

    /*
     * ----------------------------------------------------------
     * SANITIZATION
     * ----------------------------------------------------------
     */

    bool reportSanitizationProgress(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Explicit terminal sanitization update.
     *
     * This bypasses normal throttling.
     */
    bool finishSanitization(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Explicit sanitization failure update.
     *
     * Useful when the native operation fails before the
     * normal final 100% callback.
     */
    bool failSanitization(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message);

    /*
     * ----------------------------------------------------------
     * FORENSICS
     * ----------------------------------------------------------
     */

    bool reportForensicProgress(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Explicit terminal forensic update.
     *
     * This bypasses normal throttling.
     */
    bool finishForensic(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message = {});

    /*
     * Explicit forensic failure update.
     */
    bool failForensic(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message);

    /*
     * Disable all future network reporting.
     *
     * This does not affect the native operation.
     */
    void disable();

    bool enabled() const;

private:
    OperationType operationType_;

    /*
     * Backend resource identifier.
     *
     * SANITIZATION:
     *     SanitizationRequest.requestId
     *
     * FORENSIC:
     *     ForensicCase.caseId
     */
    std::string resourceId_;

    /*
     * Native execution identifier.
     */
    std::string operationId_;

    Config config_;

    bool enabled_ = false;

    std::uint64_t lastSentAtMs_ = 0;

    /*
     * Last successfully reported percentage.
     *
     * This is only useful for diagnostics/throttling state.
     * It is never treated as authoritative operation progress.
     */
    int lastPercentage_ = -1;

    bool shouldSend(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        bool force) const;

    bool sendSanitizationRequest(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes,
        const std::string& phase,
        const std::string& message,
        const std::string& status,
        bool force);

    bool sendForensicRequest(
        std::uint64_t bytesScanned,
        std::uint64_t totalBytes,
        std::uint64_t candidatesFound,
        std::uint64_t recoveredArtifacts,
        std::uint64_t validatedArtifacts,
        std::uint64_t rejectedArtifacts,
        std::uint64_t highConfidenceArtifacts,
        std::uint64_t recoveredBytes,
        const std::string& phase,
        const std::string& message,
        const std::string& status,
        bool force);

    static std::uint64_t nowMs();

    static int calculatePercentage(
        std::uint64_t processedBytes,
        std::uint64_t totalBytes);

    static std::string escapeJson(
        const std::string& value);

    static std::string joinUrl(
        const std::string& baseUrl,
        const std::string& path);

    /*
     * HTTP method is PATCH because the backend live-progress
     * routes are PATCH endpoints.
     */
    bool patchJson(
        const std::string& url,
        const std::string& jsonBody);
};